language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
  # - oraclejdk11
os:
  - linux
cache:
  directories:
    - $HOME/.m2
script:
  - ./scripts/build.sh
after_success:
  - mvn coveralls:report
